language: generic
services:
  - docker
before_install: docker-compose -f docker-compose.test.yml --env-file .env.test build
install:
  - docker-compose -f docker-compose.test.yml --env-file .env.test up -d
script: docker-compose -f docker-compose.test.yml --env-file .env.test run --rm test
after_success: bash <(curl -s https://codecov.io/bash)
